const stages = [
  { title:'Заключаем годовой контракт', body:'Обсуждаем потребности вашей семьи и условия годового сопровождения. Заключаем контракт — с этого начинается работа вашей постоянной медицинской команды.' },
  { title:'Собираем медицинскую историю', body:'Объединяем результаты анализов и обследований, заключения врачей, назначения, сведения о перенесённых заболеваниях и другие медицинские данные в единую историю здоровья.' },
  { title:'Проводим первичную медицинскую оценку', body:'Анализируем текущее состояние здоровья, образ жизни, индивидуальные и наследственные факторы риска, проводим генетическое исследование.' },
  { title:'Формируем персональный план здоровья', body:'Определяем необходимый объём медицинского наблюдения: обследования, скрининги, вакцинацию, контроль хронических состояний и значимых факторов риска. Только действительно необходимое, без лишних назначений.' },
  { title:'Наблюдаем в динамике', body:'Контролируем сроки и значимые изменения. Возвращаемся к важным вопросам тогда, когда это необходимо — без необходимости держать медицинский план в памяти самостоятельно.' },
  { title:'Решаем возникающие медицинские вопросы', body:'От нового симптома или изменения лабораторных показателей до сложного диагноза, госпитализации или хирургического лечения.' },
  { title:'Подключаем внешнюю экспертизу', body:'При необходимости находим лучшего в стране специалиста, звездного профессора или лечебное учреждение с уникальным оборудованием, подходящее для конкретной клинической задачи, и передаём ему необходимый медицинский контекст.' },
  { title:'Сохраняем непрерывность', body:'Получаем результаты консультаций, обследований и лечения и учитываем их при дальнейшем наблюдении.' },
];
const variants = [
  { id:'reference', number:'Исходный блок', name:'Точка отсчёта', idea:'Текущая версия с восемью смещёнными пунктами. Она здесь как ориентир по масштабу, шрифтам, цвету и содержанию.', type:'reference' },
  { id:'variant-1', number:'Вариант 01 · выбран для сайта', name:'Линия оживает', idea:'Сохраняем знакомую геометрию таймфрейма. При прокрутке каждый пункт мягко входит слева направо. Подробный текст раскрывается внутри карточки.', type:'reveal' },
  { id:'variant-2', number:'Вариант 02', name:'Передача заботы', idea:'Маршрут становится непрерывной нитью. При выборе этапа акцент переходит по линии, а подробность появляется рядом, не раздвигая весь блок.', type:'thread' },
  { id:'variant-3', number:'Вариант 03', name:'Восемь граней', idea:'Объёмная версия: карточки слегка поворачиваются в 3D при наведении. Нажатие переворачивает выбранный пункт и показывает подробный текст на обороте.', type:'depth' },
  { id:'variant-4', number:'Вариант 04', name:'Медицинское досье', idea:'Восемь этапов — вкладки одного дела семьи. Номер и название видны сразу, а на выбранном листе появляется крупное объяснение.', type:'dossier' },
  { id:'variant-5', number:'Вариант 05', name:'Живая шкала', idea:'Плавная горизонтальная лента. Этапы переходят один в другой, но посетитель управляет темпом стрелками и может выбрать любой пункт на мини-шкале.', type:'ribbon' },
];
const pad = i => String(i+1).padStart(2,'0');
const plus = '<span class="plus" aria-hidden="true"><svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="M7 2v10M2 7h10"/></svg></span>';
const heading = '<div class="section-heading"><h2>Как работает Медицинский Family Office</h2><img src="assets/clover.svg" alt=""></div>';
const sharedList = () => `<ol class="process-list">${stages.map((stage,i)=>`<li><details class="stage-card"><summary><h3>${stage.title}</h3>${plus}</summary><div class="stage-answer"><p>${stage.body}</p></div></details></li>`).join('')}</ol>`;
const thread = () => `<div class="thread-layout"><div class="thread-rail"><div class="thread-line"></div>${stages.map((stage,i)=>`<button type="button" class="thread-step" data-step="${i}"><span>${pad(i)}</span><b>${stage.title}</b></button>`).join('')}</div><div class="thread-detail"><div class="thread-detail-inner"><span class="detail-kicker">ЭТАП <span data-number>01</span> / 08</span><span class="thread-big-number" data-big-number>01</span><h3 data-title></h3><p data-body></p><div class="detail-foot">Одна команда знает всю историю семьи <span>✳</span></div></div></div></div>`;
const depth = () => `<div class="depth-intro">Наведите или нажмите на один из этапов <span>↘</span></div><div class="depth-grid">${stages.map((stage,i)=>`<button class="flip-card" type="button" data-flip="${i}" aria-label="${pad(i)}. ${stage.title}. Открыть описание" aria-pressed="false"><span class="flip-inner"><span class="flip-face flip-front"><span class="flip-top">${pad(i)} <span>✳</span></span><strong>${stage.title}</strong><span class="flip-bottom">Подробнее <span>↗</span></span></span><span class="flip-face flip-back"><span class="flip-top">${pad(i)} / 08 <span>↶</span></span><strong>${stage.title}</strong><span class="flip-copy">${stage.body}</span></span></span></button>`).join('')}</div>`;
const dossier = () => `<div class="dossier-layout"><div class="dossier-tabs" role="tablist" aria-label="Этапы работы">${stages.map((stage,i)=>`<button type="button" role="tab" data-step="${i}" id="dossier-tab-${i}" aria-controls="dossier-panel"><span>${pad(i)}</span><b>${stage.title}</b><i>↗</i></button>`).join('')}</div><div class="dossier-paper" role="tabpanel" id="dossier-panel" aria-labelledby="dossier-tab-0"><div class="paper-overline">ЕС КЛИНИКА <span>МЕДИЦИНСКИЙ FAMILY OFFICE</span></div><div class="paper-index" data-number>01</div><div class="paper-content"><span>ЭТАП РАБОТЫ / <span data-small-number>01</span></span><h3 data-title></h3><p data-body></p></div><div class="paper-footer"><span>У каждой семьи — единая история здоровья</span><span>✳</span></div></div></div>`;
const ribbon = () => `<div class="ribbon-layout"><div class="ribbon-frame"><div class="ribbon-top"><span>МАРШРУТ СОПРОВОЖДЕНИЯ</span><span><span data-small-number>01</span> / 08</span></div><div class="ribbon-content"><span class="ribbon-ghost" data-number>01</span><div><span class="ribbon-label">MEDICAL FAMILY OFFICE / ЭТАП</span><h3 data-title></h3><p data-body></p></div></div><div class="ribbon-controls"><button type="button" data-prev aria-label="Предыдущий этап">←</button><span>Листайте этапы</span><button type="button" data-next aria-label="Следующий этап">→</button></div></div><div class="ribbon-scale" role="group" aria-label="Выбрать этап">${stages.map((stage,i)=>`<button type="button" data-step="${i}" aria-label="${pad(i)}. ${stage.title}"><span>${pad(i)}</span></button>`).join('')}</div></div>`;
const bodyFor = v => ({thread,depth,dossier,ribbon}[v.type]?.() ?? sharedList());
document.querySelector('#showcase').innerHTML = variants.map(v=>`<section class="example" id="${v.id}"><div class="variant-label"><div><span>${v.number}</span><h2>${v.name}</h2><p>${v.idea}</p></div><a href="#${v.id}" aria-label="Ссылка на вариант">↗</a></div><div class="process-block ${v.type}">${heading}${bodyFor(v)}</div></section>`).join('');
document.querySelectorAll('.stage-card').forEach(el=>el.addEventListener('toggle',()=>el.dataset.expanded=String(el.open)));
const animated=document.querySelector('.process-block.reveal');
const revealObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){animated.classList.add('entered');revealObserver.disconnect()}},{threshold:.16});
revealObserver.observe(animated);
function setSelected(root,index){
  root.dataset.active=String(index);
  root.querySelectorAll('[data-step]').forEach(button=>{const selected=Number(button.dataset.step)===index;button.classList.toggle('selected',selected);button.setAttribute('aria-selected',String(selected));button.setAttribute('aria-pressed',String(selected))});
  root.querySelectorAll('[data-number],[data-big-number],[data-small-number]').forEach(el=>el.textContent=pad(index));
  root.querySelector('[data-title]').textContent=stages[index].title;
  root.querySelector('[data-body]').textContent=stages[index].body;
  root.querySelector('[role="tabpanel"]')?.setAttribute('aria-labelledby',`dossier-tab-${index}`);
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)root.querySelector('.thread-detail-inner,.dossier-paper,.ribbon-content')?.animate([{opacity:.5,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:430,easing:'cubic-bezier(.22,1,.36,1)'});
}
for(const selector of ['.thread','.dossier','.ribbon']){const root=document.querySelector(selector);root.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>setSelected(root,Number(button.dataset.step))));root.querySelector('[data-prev]')?.addEventListener('click',()=>setSelected(root,(Number(root.dataset.active)+7)%8));root.querySelector('[data-next]')?.addEventListener('click',()=>setSelected(root,(Number(root.dataset.active)+1)%8));setSelected(root,0)}
document.querySelectorAll('.flip-card').forEach(card=>{card.addEventListener('click',()=>{const open=card.classList.toggle('flipped');card.setAttribute('aria-pressed',String(open));card.setAttribute('aria-label',`${pad(Number(card.dataset.flip))}. ${stages[Number(card.dataset.flip)].title}. ${open?'Вернуться к названию':'Открыть описание'}`)});card.addEventListener('pointermove',event=>{if(card.classList.contains('flipped')||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=card.getBoundingClientRect();card.style.setProperty('--tilt-x',`${((event.clientY-r.top)/r.height-.5)*-9}deg`);card.style.setProperty('--tilt-y',`${((event.clientX-r.left)/r.width-.5)*9}deg`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--tilt-x','0deg');card.style.setProperty('--tilt-y','0deg')})});
